target 'iHappy' do

pod 'AFNetworking'
pod 'GDataXML-HTML', '~> 1.3.0'
pod 'Reachability', '~> 3.2'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.2'
pod 'Masonry', '~> 0.6.3'
pod 'IQKeyboardManager', '~> 3.3.2'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'YYModel', '~> 1.0.4'
pod 'JSONModel'
pod 'WMPageController'
#pod 'ZFPlayer', '~> 2.1.3'

#AOP面向切面思想
pod 'AspectsV1.4.2', '~> 1.4.2'
pod 'JDStatusBarNotification'
pod 'CWStackController', :git => 'https://github.com/guojiubo/CWStackController.git', :commit => '8ff182c2f4e6b4cc31b9357f2a31f6bde456ef87'
pod 'CWFoundation', :git => 'https://github.com/guojiubo/CWFoundation.git', :commit => '2352449291499091f4e4a82877ec57c9070ced35'

pod 'hpple'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

##ReactiveCocoa，函数式编程
#use_frameworks!
#pod 'ReactiveCocoa', '~> 4.2.1'

end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['ENABLE_BITCODE'] = 'NO'
#        end
#    end
#end
